# Generated by Django 2.1.1 on 2018-11-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_group_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linegroup',
            name='emba_group_id',
        ),
        migrations.AddField(
            model_name='linegroup',
            name='emba_group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
